// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Song struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page                 string   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Audio                string   `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Bitrate              int32    `protobuf:"varint,6,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Song) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Song) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Song) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

func (m *Song) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Song) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type SongPlaylist struct {
	Songs                []*Song  `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongPlaylist) Reset()         { *m = SongPlaylist{} }
func (m *SongPlaylist) String() string { return proto.CompactTextString(m) }
func (*SongPlaylist) ProtoMessage()    {}
func (*SongPlaylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *SongPlaylist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongPlaylist.Unmarshal(m, b)
}
func (m *SongPlaylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongPlaylist.Marshal(b, m, deterministic)
}
func (m *SongPlaylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongPlaylist.Merge(m, src)
}
func (m *SongPlaylist) XXX_Size() int {
	return xxx_messageInfo_SongPlaylist.Size(m)
}
func (m *SongPlaylist) XXX_DiscardUnknown() {
	xxx_messageInfo_SongPlaylist.DiscardUnknown(m)
}

var xxx_messageInfo_SongPlaylist proto.InternalMessageInfo

func (m *SongPlaylist) GetSongs() []*Song {
	if m != nil {
		return m.Songs
	}
	return nil
}

type AudioResponse struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioResponse) Reset()         { *m = AudioResponse{} }
func (m *AudioResponse) String() string { return proto.CompactTextString(m) }
func (*AudioResponse) ProtoMessage()    {}
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *AudioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioResponse.Unmarshal(m, b)
}
func (m *AudioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioResponse.Marshal(b, m, deterministic)
}
func (m *AudioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioResponse.Merge(m, src)
}
func (m *AudioResponse) XXX_Size() int {
	return xxx_messageInfo_AudioResponse.Size(m)
}
func (m *AudioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AudioResponse proto.InternalMessageInfo

func (m *AudioResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type OutputRequest struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputRequest) Reset()         { *m = OutputRequest{} }
func (m *OutputRequest) String() string { return proto.CompactTextString(m) }
func (*OutputRequest) ProtoMessage()    {}
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{3}
}

func (m *OutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputRequest.Unmarshal(m, b)
}
func (m *OutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputRequest.Marshal(b, m, deterministic)
}
func (m *OutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputRequest.Merge(m, src)
}
func (m *OutputRequest) XXX_Size() int {
	return xxx_messageInfo_OutputRequest.Size(m)
}
func (m *OutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutputRequest proto.InternalMessageInfo

func (m *OutputRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type OutputResponse struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputResponse) Reset()         { *m = OutputResponse{} }
func (m *OutputResponse) String() string { return proto.CompactTextString(m) }
func (*OutputResponse) ProtoMessage()    {}
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{4}
}

func (m *OutputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputResponse.Unmarshal(m, b)
}
func (m *OutputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputResponse.Marshal(b, m, deterministic)
}
func (m *OutputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputResponse.Merge(m, src)
}
func (m *OutputResponse) XXX_Size() int {
	return xxx_messageInfo_OutputResponse.Size(m)
}
func (m *OutputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OutputResponse proto.InternalMessageInfo

func (m *OutputResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type StatusResponse struct {
	Output               bool     `protobuf:"varint,1,opt,name=output,proto3" json:"output,omitempty"`
	Audio                bool     `protobuf:"varint,2,opt,name=audio,proto3" json:"audio,omitempty"`
	Stream               bool     `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetOutput() bool {
	if m != nil {
		return m.Output
	}
	return false
}

func (m *StatusResponse) GetAudio() bool {
	if m != nil {
		return m.Audio
	}
	return false
}

func (m *StatusResponse) GetStream() bool {
	if m != nil {
		return m.Stream
	}
	return false
}

type SDP struct {
	Sdp                  string   `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDP) Reset()         { *m = SDP{} }
func (m *SDP) String() string { return proto.CompactTextString(m) }
func (*SDP) ProtoMessage()    {}
func (*SDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{6}
}

func (m *SDP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDP.Unmarshal(m, b)
}
func (m *SDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDP.Marshal(b, m, deterministic)
}
func (m *SDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDP.Merge(m, src)
}
func (m *SDP) XXX_Size() int {
	return xxx_messageInfo_SDP.Size(m)
}
func (m *SDP) XXX_DiscardUnknown() {
	xxx_messageInfo_SDP.DiscardUnknown(m)
}

var xxx_messageInfo_SDP proto.InternalMessageInfo

func (m *SDP) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type StatusNCSResponse struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusNCSResponse) Reset()         { *m = StatusNCSResponse{} }
func (m *StatusNCSResponse) String() string { return proto.CompactTextString(m) }
func (*StatusNCSResponse) ProtoMessage()    {}
func (*StatusNCSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7}
}

func (m *StatusNCSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusNCSResponse.Unmarshal(m, b)
}
func (m *StatusNCSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusNCSResponse.Marshal(b, m, deterministic)
}
func (m *StatusNCSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusNCSResponse.Merge(m, src)
}
func (m *StatusNCSResponse) XXX_Size() int {
	return xxx_messageInfo_StatusNCSResponse.Size(m)
}
func (m *StatusNCSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusNCSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusNCSResponse proto.InternalMessageInfo

func (m *StatusNCSResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type TwitchStreamKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwitchStreamKey) Reset()         { *m = TwitchStreamKey{} }
func (m *TwitchStreamKey) String() string { return proto.CompactTextString(m) }
func (*TwitchStreamKey) ProtoMessage()    {}
func (*TwitchStreamKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{8}
}

func (m *TwitchStreamKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwitchStreamKey.Unmarshal(m, b)
}
func (m *TwitchStreamKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwitchStreamKey.Marshal(b, m, deterministic)
}
func (m *TwitchStreamKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwitchStreamKey.Merge(m, src)
}
func (m *TwitchStreamKey) XXX_Size() int {
	return xxx_messageInfo_TwitchStreamKey.Size(m)
}
func (m *TwitchStreamKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TwitchStreamKey.DiscardUnknown(m)
}

var xxx_messageInfo_TwitchStreamKey proto.InternalMessageInfo

func (m *TwitchStreamKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TwitchStreamKey) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type DevCredentials struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevCredentials) Reset()         { *m = DevCredentials{} }
func (m *DevCredentials) String() string { return proto.CompactTextString(m) }
func (*DevCredentials) ProtoMessage()    {}
func (*DevCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{9}
}

func (m *DevCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevCredentials.Unmarshal(m, b)
}
func (m *DevCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevCredentials.Marshal(b, m, deterministic)
}
func (m *DevCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevCredentials.Merge(m, src)
}
func (m *DevCredentials) XXX_Size() int {
	return xxx_messageInfo_DevCredentials.Size(m)
}
func (m *DevCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_DevCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_DevCredentials proto.InternalMessageInfo

func (m *DevCredentials) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *DevCredentials) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *DevCredentials) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type UserAuth struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{10}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Overlay struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	PointX               int32    `protobuf:"varint,5,opt,name=pointX,proto3" json:"pointX,omitempty"`
	PointY               int32    `protobuf:"varint,6,opt,name=pointY,proto3" json:"pointY,omitempty"`
	Show                 bool     `protobuf:"varint,7,opt,name=show,proto3" json:"show,omitempty"`
	CoverId              string   `protobuf:"bytes,8,opt,name=coverId,proto3" json:"coverId,omitempty"`
	Text                 string   `protobuf:"bytes,9,opt,name=text,proto3" json:"text,omitempty"`
	FontFamily           string   `protobuf:"bytes,10,opt,name=fontFamily,proto3" json:"fontFamily,omitempty"`
	FontSize             int32    `protobuf:"varint,11,opt,name=fontSize,proto3" json:"fontSize,omitempty"`
	LineHeight           float64  `protobuf:"fixed64,12,opt,name=lineHeight,proto3" json:"lineHeight,omitempty"`
	TextColor            string   `protobuf:"bytes,13,opt,name=textColor,proto3" json:"textColor,omitempty"`
	TextAlign            string   `protobuf:"bytes,14,opt,name=textAlign,proto3" json:"textAlign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Overlay) Reset()         { *m = Overlay{} }
func (m *Overlay) String() string { return proto.CompactTextString(m) }
func (*Overlay) ProtoMessage()    {}
func (*Overlay) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{11}
}

func (m *Overlay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Overlay.Unmarshal(m, b)
}
func (m *Overlay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Overlay.Marshal(b, m, deterministic)
}
func (m *Overlay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Overlay.Merge(m, src)
}
func (m *Overlay) XXX_Size() int {
	return xxx_messageInfo_Overlay.Size(m)
}
func (m *Overlay) XXX_DiscardUnknown() {
	xxx_messageInfo_Overlay.DiscardUnknown(m)
}

var xxx_messageInfo_Overlay proto.InternalMessageInfo

func (m *Overlay) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Overlay) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Overlay) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Overlay) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Overlay) GetPointX() int32 {
	if m != nil {
		return m.PointX
	}
	return 0
}

func (m *Overlay) GetPointY() int32 {
	if m != nil {
		return m.PointY
	}
	return 0
}

func (m *Overlay) GetShow() bool {
	if m != nil {
		return m.Show
	}
	return false
}

func (m *Overlay) GetCoverId() string {
	if m != nil {
		return m.CoverId
	}
	return ""
}

func (m *Overlay) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Overlay) GetFontFamily() string {
	if m != nil {
		return m.FontFamily
	}
	return ""
}

func (m *Overlay) GetFontSize() int32 {
	if m != nil {
		return m.FontSize
	}
	return 0
}

func (m *Overlay) GetLineHeight() float64 {
	if m != nil {
		return m.LineHeight
	}
	return 0
}

func (m *Overlay) GetTextColor() string {
	if m != nil {
		return m.TextColor
	}
	return ""
}

func (m *Overlay) GetTextAlign() string {
	if m != nil {
		return m.TextAlign
	}
	return ""
}

type Overlays struct {
	Overlays             []*Overlay `protobuf:"bytes,1,rep,name=overlays,proto3" json:"overlays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Overlays) Reset()         { *m = Overlays{} }
func (m *Overlays) String() string { return proto.CompactTextString(m) }
func (*Overlays) ProtoMessage()    {}
func (*Overlays) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{12}
}

func (m *Overlays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Overlays.Unmarshal(m, b)
}
func (m *Overlays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Overlays.Marshal(b, m, deterministic)
}
func (m *Overlays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Overlays.Merge(m, src)
}
func (m *Overlays) XXX_Size() int {
	return xxx_messageInfo_Overlays.Size(m)
}
func (m *Overlays) XXX_DiscardUnknown() {
	xxx_messageInfo_Overlays.DiscardUnknown(m)
}

var xxx_messageInfo_Overlays proto.InternalMessageInfo

func (m *Overlays) GetOverlays() []*Overlay {
	if m != nil {
		return m.Overlays
	}
	return nil
}

func init() {
	proto.RegisterType((*Song)(nil), "service.Song")
	proto.RegisterType((*SongPlaylist)(nil), "service.SongPlaylist")
	proto.RegisterType((*AudioResponse)(nil), "service.AudioResponse")
	proto.RegisterType((*OutputRequest)(nil), "service.OutputRequest")
	proto.RegisterType((*OutputResponse)(nil), "service.OutputResponse")
	proto.RegisterType((*StatusResponse)(nil), "service.StatusResponse")
	proto.RegisterType((*SDP)(nil), "service.SDP")
	proto.RegisterType((*StatusNCSResponse)(nil), "service.StatusNCSResponse")
	proto.RegisterType((*TwitchStreamKey)(nil), "service.TwitchStreamKey")
	proto.RegisterType((*DevCredentials)(nil), "service.DevCredentials")
	proto.RegisterType((*UserAuth)(nil), "service.UserAuth")
	proto.RegisterType((*Overlay)(nil), "service.Overlay")
	proto.RegisterType((*Overlays)(nil), "service.Overlays")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 922 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5f, 0x6f, 0xdc, 0xc4,
	0x17, 0xdd, 0xff, 0xbb, 0xb9, 0x49, 0xb6, 0xcd, 0xb4, 0x4d, 0xfd, 0xdb, 0x1f, 0xaa, 0x22, 0x57,
	0x40, 0x24, 0xd0, 0x46, 0x6a, 0x5f, 0x10, 0x95, 0xa0, 0xcb, 0x26, 0x81, 0x80, 0x9a, 0x46, 0xde,
	0x16, 0x01, 0xe2, 0x65, 0x62, 0xdf, 0xee, 0x8e, 0xe2, 0xf5, 0x98, 0xf1, 0x78, 0xb7, 0xe6, 0x33,
	0xf0, 0x11, 0x79, 0xe5, 0x7b, 0xa0, 0xf9, 0x63, 0xaf, 0xbd, 0xe0, 0x50, 0xe8, 0xdb, 0x9c, 0x3b,
	0xf7, 0x9e, 0x7b, 0xee, 0x78, 0xe6, 0x18, 0x60, 0x49, 0x59, 0x34, 0x8e, 0x05, 0x97, 0x9c, 0xf4,
	0x13, 0x14, 0x2b, 0xe6, 0xe3, 0xe8, 0xff, 0x73, 0xce, 0xe7, 0x21, 0x9e, 0xe8, 0xf0, 0x75, 0xfa,
	0xe6, 0x04, 0x97, 0xb1, 0xcc, 0x4c, 0x96, 0xfb, 0x5b, 0x13, 0x3a, 0x33, 0x1e, 0xcd, 0x09, 0x81,
	0x4e, 0x44, 0x97, 0xe8, 0x34, 0x8f, 0x9a, 0xc7, 0x3b, 0x9e, 0x5e, 0xab, 0x58, 0x4c, 0xe7, 0xe8,
	0xb4, 0x4c, 0x4c, 0xad, 0xc9, 0x21, 0xf4, 0x68, 0x2a, 0x17, 0x5c, 0x38, 0x6d, 0x1d, 0xb5, 0x88,
	0xdc, 0x87, 0x2e, 0x4d, 0x03, 0xc6, 0x9d, 0x8e, 0x0e, 0x1b, 0xa0, 0xa2, 0x3e, 0x5f, 0xa1, 0x70,
	0xba, 0x26, 0xaa, 0x01, 0x71, 0xa0, 0x7f, 0xcd, 0xa4, 0xa0, 0x12, 0x9d, 0xde, 0x51, 0xf3, 0xb8,
	0xeb, 0xe5, 0xd0, 0x7d, 0x0a, 0x7b, 0x4a, 0xcd, 0x55, 0x48, 0xb3, 0x90, 0x25, 0x92, 0x3c, 0x86,
	0x6e, 0xc2, 0xa3, 0x79, 0xe2, 0x34, 0x8f, 0xda, 0xc7, 0xbb, 0x4f, 0xf6, 0xc7, 0x76, 0xa8, 0xb1,
	0xca, 0xf2, 0xcc, 0x9e, 0xfb, 0x21, 0xec, 0x4f, 0x54, 0x37, 0x0f, 0x93, 0x98, 0x47, 0x09, 0xaa,
	0xae, 0x02, 0x69, 0x90, 0xe9, 0x61, 0x06, 0x9e, 0x01, 0xee, 0x63, 0xd8, 0x7f, 0x99, 0xca, 0x38,
	0x95, 0x1e, 0xfe, 0x92, 0x62, 0x22, 0xd5, 0x78, 0x4b, 0x1e, 0x14, 0x23, 0xab, 0xb5, 0xfb, 0x11,
	0x0c, 0xf3, 0xa4, 0x5b, 0xc9, 0xbe, 0x87, 0xe1, 0x4c, 0x52, 0x99, 0x26, 0x45, 0xde, 0x21, 0xf4,
	0xb8, 0xae, 0xb4, 0x89, 0x16, 0x6d, 0x0e, 0xa6, 0x65, 0xea, 0xcd, 0xc1, 0x1c, 0x42, 0x2f, 0x91,
	0x02, 0xe9, 0x52, 0x1f, 0xe3, 0xc0, 0xb3, 0xc8, 0x7d, 0x08, 0xed, 0xd9, 0xe9, 0x15, 0xb9, 0x0b,
	0xed, 0x24, 0x88, 0xad, 0x32, 0xb5, 0x74, 0x3f, 0x81, 0x03, 0xd3, 0xf0, 0x72, 0x3a, 0x2b, 0xf7,
	0xa4, 0xbe, 0x64, 0x2b, 0xcc, 0x7b, 0x1a, 0xe4, 0x3e, 0x83, 0x3b, 0xaf, 0xd6, 0x4c, 0xfa, 0x8b,
	0x99, 0x66, 0xfd, 0x0e, 0x33, 0xc5, 0x78, 0x83, 0x59, 0xce, 0x78, 0x83, 0x59, 0xa9, 0xb8, 0x55,
	0x29, 0xfe, 0x19, 0x86, 0xa7, 0xb8, 0x9a, 0x0a, 0x0c, 0x30, 0x92, 0x8c, 0x86, 0x09, 0x19, 0xc1,
	0xc0, 0x0f, 0x19, 0x46, 0xf2, 0x22, 0xb0, 0x04, 0x05, 0xd6, 0x83, 0xa0, 0x2f, 0x50, 0xda, 0x5b,
	0x62, 0x51, 0x89, 0xbd, 0x5d, 0x61, 0x7f, 0x04, 0x83, 0xd7, 0x09, 0x8a, 0x49, 0x2a, 0x17, 0xea,
	0x03, 0xf8, 0xa5, 0x0f, 0xa0, 0xd6, 0xee, 0x1f, 0x2d, 0xe8, 0xbf, 0x5c, 0xa1, 0x08, 0x69, 0x46,
	0x86, 0xd0, 0x62, 0x79, 0xc7, 0x16, 0x0b, 0x54, 0xbe, 0xcc, 0xe2, 0xe2, 0x3e, 0xaa, 0xb5, 0x3a,
	0xde, 0x35, 0x0b, 0xe4, 0x42, 0xb7, 0xe9, 0x7a, 0x06, 0xa8, 0xee, 0x0b, 0x64, 0xf3, 0x85, 0xd4,
	0xd7, 0xb1, 0xeb, 0x59, 0xa4, 0xe2, 0x31, 0x67, 0x91, 0xfc, 0x41, 0x5f, 0xc8, 0xae, 0x67, 0x51,
	0x11, 0xff, 0xd1, 0x5e, 0x48, 0x8b, 0x54, 0xc7, 0x64, 0xc1, 0xd7, 0x4e, 0x5f, 0xcf, 0xa0, 0xd7,
	0xea, 0xf6, 0xea, 0x6b, 0x7c, 0x11, 0x38, 0x03, 0x2d, 0x24, 0x87, 0x5a, 0x1f, 0xbe, 0x95, 0xce,
	0x8e, 0xd5, 0x87, 0x6f, 0x25, 0x79, 0x04, 0xf0, 0x86, 0x47, 0xf2, 0x9c, 0x2e, 0x59, 0x98, 0x39,
	0xa0, 0x77, 0x4a, 0x11, 0x75, 0xb6, 0x0a, 0xcd, 0xd8, 0xaf, 0xe8, 0xec, 0xea, 0xde, 0x05, 0x56,
	0xb5, 0x21, 0x8b, 0xf0, 0x1b, 0x33, 0xc9, 0xde, 0x51, 0xf3, 0xb8, 0xe9, 0x95, 0x22, 0xe4, 0x03,
	0xd8, 0x51, 0x3d, 0xa6, 0x3c, 0xe4, 0xc2, 0xd9, 0xd7, 0xd4, 0x9b, 0x40, 0xbe, 0x3b, 0x09, 0xd9,
	0x3c, 0x72, 0x86, 0x9b, 0x5d, 0x1d, 0x70, 0x3f, 0x83, 0x81, 0x3d, 0xe6, 0x84, 0x7c, 0x0a, 0x03,
	0x6e, 0xd7, 0xf6, 0xa1, 0xdd, 0x2d, 0x1e, 0x9a, 0x4d, 0xf2, 0x8a, 0x8c, 0x27, 0xbf, 0x03, 0x74,
	0x5e, 0x50, 0x16, 0x91, 0x33, 0x20, 0x53, 0x81, 0x54, 0x62, 0xe5, 0xc9, 0x1e, 0x8e, 0x8d, 0xdf,
	0x8c, 0x73, 0xbf, 0x19, 0x9f, 0x29, 0xbf, 0x19, 0x3d, 0xa8, 0xbc, 0xdd, 0x3c, 0xdd, 0x6d, 0x90,
	0x73, 0xb8, 0x37, 0x4d, 0x85, 0xc0, 0x48, 0xbe, 0x1f, 0xcf, 0x19, 0x90, 0xd7, 0x71, 0xb0, 0x2d,
	0xe7, 0xef, 0xd3, 0x47, 0x35, 0xec, 0x6e, 0x83, 0x7c, 0x0c, 0xfd, 0x2b, 0x81, 0x2b, 0x86, 0x6b,
	0xb2, 0xb7, 0xa9, 0x3d, 0xbd, 0x1a, 0x55, 0x90, 0xdb, 0x20, 0x5f, 0xc2, 0xee, 0x4c, 0x52, 0x21,
	0xcd, 0x1b, 0xab, 0xd5, 0x5b, 0xdf, 0xe9, 0x0b, 0x80, 0x99, 0xe4, 0xf1, 0xfb, 0xd5, 0x53, 0x21,
	0x27, 0xc6, 0x51, 0x6a, 0xeb, 0x73, 0xd9, 0x15, 0x93, 0x74, 0x1b, 0xe4, 0xb9, 0x1d, 0xc0, 0x18,
	0x1e, 0xd9, 0x24, 0x56, 0x6c, 0x72, 0xf4, 0xf0, 0x2f, 0xf1, 0x82, 0xc1, 0x4e, 0x50, 0x10, 0xfc,
	0xdb, 0x09, 0x9e, 0x41, 0xcf, 0x98, 0x5a, 0x6d, 0xed, 0xa6, 0x79, 0xd5, 0x6e, 0xdd, 0x06, 0x99,
	0xc2, 0x9d, 0x73, 0x16, 0x05, 0x97, 0xb8, 0x56, 0x5f, 0x56, 0xf9, 0xe2, 0x7f, 0x50, 0x30, 0x81,
	0x9d, 0xc2, 0x56, 0x6b, 0xcb, 0x47, 0x5b, 0x22, 0x4a, 0x16, 0xec, 0x36, 0xc8, 0x05, 0xdc, 0xb3,
	0x66, 0x4b, 0x57, 0xb8, 0x31, 0x5c, 0xa7, 0x28, 0xda, 0xb2, 0xe2, 0x5b, 0xd4, 0x7c, 0x0b, 0xf7,
	0xa7, 0x0b, 0xf4, 0x6f, 0xb6, 0xcd, 0xbb, 0x4e, 0x58, 0x6d, 0x0f, 0x2d, 0xeb, 0xc1, 0x29, 0x86,
	0x28, 0xf1, 0x5d, 0xc9, 0xea, 0x65, 0xbd, 0x00, 0x47, 0xcd, 0x66, 0x88, 0xb6, 0xfe, 0x0d, 0x9b,
	0x0f, 0x54, 0xdd, 0xb8, 0x85, 0xee, 0x12, 0xfe, 0x57, 0x9a, 0x72, 0x8b, 0xef, 0x9f, 0x2f, 0x42,
	0xb5, 0x40, 0xf3, 0x8d, 0xca, 0x93, 0xbe, 0x23, 0x61, 0xbd, 0xbe, 0xe7, 0x70, 0x60, 0x98, 0x26,
	0xbe, 0x8f, 0x49, 0xf2, 0x8a, 0xdf, 0x60, 0x44, 0x0e, 0x8a, 0xfe, 0xf9, 0xef, 0xeb, 0x16, 0x86,
	0xcf, 0x61, 0xf7, 0x6b, 0x94, 0x85, 0xbf, 0xd6, 0x49, 0x38, 0xd8, 0x76, 0xd9, 0xc4, 0x6d, 0x7c,
	0xd5, 0xfb, 0xa9, 0x33, 0x3e, 0x89, 0xaf, 0xaf, 0x7b, 0x3a, 0xf9, 0xe9, 0x9f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x27, 0x2d, 0xdd, 0x59, 0xd4, 0x09, 0x00, 0x00,
}
