// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Song struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page                 string   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Audio                string   `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Bitrate              int32    `protobuf:"varint,6,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Song) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Song) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Song) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

func (m *Song) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Song) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type SongPlaylist struct {
	Songs                []*Song  `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongPlaylist) Reset()         { *m = SongPlaylist{} }
func (m *SongPlaylist) String() string { return proto.CompactTextString(m) }
func (*SongPlaylist) ProtoMessage()    {}
func (*SongPlaylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *SongPlaylist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongPlaylist.Unmarshal(m, b)
}
func (m *SongPlaylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongPlaylist.Marshal(b, m, deterministic)
}
func (m *SongPlaylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongPlaylist.Merge(m, src)
}
func (m *SongPlaylist) XXX_Size() int {
	return xxx_messageInfo_SongPlaylist.Size(m)
}
func (m *SongPlaylist) XXX_DiscardUnknown() {
	xxx_messageInfo_SongPlaylist.DiscardUnknown(m)
}

var xxx_messageInfo_SongPlaylist proto.InternalMessageInfo

func (m *SongPlaylist) GetSongs() []*Song {
	if m != nil {
		return m.Songs
	}
	return nil
}

type AudioResponse struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioResponse) Reset()         { *m = AudioResponse{} }
func (m *AudioResponse) String() string { return proto.CompactTextString(m) }
func (*AudioResponse) ProtoMessage()    {}
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *AudioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioResponse.Unmarshal(m, b)
}
func (m *AudioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioResponse.Marshal(b, m, deterministic)
}
func (m *AudioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioResponse.Merge(m, src)
}
func (m *AudioResponse) XXX_Size() int {
	return xxx_messageInfo_AudioResponse.Size(m)
}
func (m *AudioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AudioResponse proto.InternalMessageInfo

func (m *AudioResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type StreamResponse struct {
	Volume               float64         `protobuf:"fixed64,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Status               *StatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{3}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *StreamResponse) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

type StatusResponse struct {
	Preview              bool     `protobuf:"varint,1,opt,name=preview,proto3" json:"preview,omitempty"`
	Audio                bool     `protobuf:"varint,2,opt,name=audio,proto3" json:"audio,omitempty"`
	Stream               bool     `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{4}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetPreview() bool {
	if m != nil {
		return m.Preview
	}
	return false
}

func (m *StatusResponse) GetAudio() bool {
	if m != nil {
		return m.Audio
	}
	return false
}

func (m *StatusResponse) GetStream() bool {
	if m != nil {
		return m.Stream
	}
	return false
}

type SDP struct {
	Sdp                  string   `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDP) Reset()         { *m = SDP{} }
func (m *SDP) String() string { return proto.CompactTextString(m) }
func (*SDP) ProtoMessage()    {}
func (*SDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5}
}

func (m *SDP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDP.Unmarshal(m, b)
}
func (m *SDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDP.Marshal(b, m, deterministic)
}
func (m *SDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDP.Merge(m, src)
}
func (m *SDP) XXX_Size() int {
	return xxx_messageInfo_SDP.Size(m)
}
func (m *SDP) XXX_DiscardUnknown() {
	xxx_messageInfo_SDP.DiscardUnknown(m)
}

var xxx_messageInfo_SDP proto.InternalMessageInfo

func (m *SDP) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type StatusNCSResponse struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusNCSResponse) Reset()         { *m = StatusNCSResponse{} }
func (m *StatusNCSResponse) String() string { return proto.CompactTextString(m) }
func (*StatusNCSResponse) ProtoMessage()    {}
func (*StatusNCSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{6}
}

func (m *StatusNCSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusNCSResponse.Unmarshal(m, b)
}
func (m *StatusNCSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusNCSResponse.Marshal(b, m, deterministic)
}
func (m *StatusNCSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusNCSResponse.Merge(m, src)
}
func (m *StatusNCSResponse) XXX_Size() int {
	return xxx_messageInfo_StatusNCSResponse.Size(m)
}
func (m *StatusNCSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusNCSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusNCSResponse proto.InternalMessageInfo

func (m *StatusNCSResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type TwitchStreamKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwitchStreamKey) Reset()         { *m = TwitchStreamKey{} }
func (m *TwitchStreamKey) String() string { return proto.CompactTextString(m) }
func (*TwitchStreamKey) ProtoMessage()    {}
func (*TwitchStreamKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7}
}

func (m *TwitchStreamKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwitchStreamKey.Unmarshal(m, b)
}
func (m *TwitchStreamKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwitchStreamKey.Marshal(b, m, deterministic)
}
func (m *TwitchStreamKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwitchStreamKey.Merge(m, src)
}
func (m *TwitchStreamKey) XXX_Size() int {
	return xxx_messageInfo_TwitchStreamKey.Size(m)
}
func (m *TwitchStreamKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TwitchStreamKey.DiscardUnknown(m)
}

var xxx_messageInfo_TwitchStreamKey proto.InternalMessageInfo

func (m *TwitchStreamKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TwitchStreamKey) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type DevCredentials struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevCredentials) Reset()         { *m = DevCredentials{} }
func (m *DevCredentials) String() string { return proto.CompactTextString(m) }
func (*DevCredentials) ProtoMessage()    {}
func (*DevCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{8}
}

func (m *DevCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevCredentials.Unmarshal(m, b)
}
func (m *DevCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevCredentials.Marshal(b, m, deterministic)
}
func (m *DevCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevCredentials.Merge(m, src)
}
func (m *DevCredentials) XXX_Size() int {
	return xxx_messageInfo_DevCredentials.Size(m)
}
func (m *DevCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_DevCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_DevCredentials proto.InternalMessageInfo

func (m *DevCredentials) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *DevCredentials) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *DevCredentials) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type UserAuth struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{9}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type StreamParametersResponse struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps                  int32    `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	Preset               string   `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`
	Volume               float64  `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamParametersResponse) Reset()         { *m = StreamParametersResponse{} }
func (m *StreamParametersResponse) String() string { return proto.CompactTextString(m) }
func (*StreamParametersResponse) ProtoMessage()    {}
func (*StreamParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{10}
}

func (m *StreamParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamParametersResponse.Unmarshal(m, b)
}
func (m *StreamParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamParametersResponse.Marshal(b, m, deterministic)
}
func (m *StreamParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamParametersResponse.Merge(m, src)
}
func (m *StreamParametersResponse) XXX_Size() int {
	return xxx_messageInfo_StreamParametersResponse.Size(m)
}
func (m *StreamParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamParametersResponse proto.InternalMessageInfo

func (m *StreamParametersResponse) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *StreamParametersResponse) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *StreamParametersResponse) GetFps() int32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *StreamParametersResponse) GetPreset() string {
	if m != nil {
		return m.Preset
	}
	return ""
}

func (m *StreamParametersResponse) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type SaveStreamParametersRequest struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps                  int32    `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	Preset               string   `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveStreamParametersRequest) Reset()         { *m = SaveStreamParametersRequest{} }
func (m *SaveStreamParametersRequest) String() string { return proto.CompactTextString(m) }
func (*SaveStreamParametersRequest) ProtoMessage()    {}
func (*SaveStreamParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{11}
}

func (m *SaveStreamParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveStreamParametersRequest.Unmarshal(m, b)
}
func (m *SaveStreamParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveStreamParametersRequest.Marshal(b, m, deterministic)
}
func (m *SaveStreamParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveStreamParametersRequest.Merge(m, src)
}
func (m *SaveStreamParametersRequest) XXX_Size() int {
	return xxx_messageInfo_SaveStreamParametersRequest.Size(m)
}
func (m *SaveStreamParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveStreamParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveStreamParametersRequest proto.InternalMessageInfo

func (m *SaveStreamParametersRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *SaveStreamParametersRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SaveStreamParametersRequest) GetFps() int32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *SaveStreamParametersRequest) GetPreset() string {
	if m != nil {
		return m.Preset
	}
	return ""
}

type YoutubeStreamKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YoutubeStreamKey) Reset()         { *m = YoutubeStreamKey{} }
func (m *YoutubeStreamKey) String() string { return proto.CompactTextString(m) }
func (*YoutubeStreamKey) ProtoMessage()    {}
func (*YoutubeStreamKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{12}
}

func (m *YoutubeStreamKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YoutubeStreamKey.Unmarshal(m, b)
}
func (m *YoutubeStreamKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YoutubeStreamKey.Marshal(b, m, deterministic)
}
func (m *YoutubeStreamKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YoutubeStreamKey.Merge(m, src)
}
func (m *YoutubeStreamKey) XXX_Size() int {
	return xxx_messageInfo_YoutubeStreamKey.Size(m)
}
func (m *YoutubeStreamKey) XXX_DiscardUnknown() {
	xxx_messageInfo_YoutubeStreamKey.DiscardUnknown(m)
}

var xxx_messageInfo_YoutubeStreamKey proto.InternalMessageInfo

func (m *YoutubeStreamKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type YoutubeStreamUrl struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YoutubeStreamUrl) Reset()         { *m = YoutubeStreamUrl{} }
func (m *YoutubeStreamUrl) String() string { return proto.CompactTextString(m) }
func (*YoutubeStreamUrl) ProtoMessage()    {}
func (*YoutubeStreamUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{13}
}

func (m *YoutubeStreamUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YoutubeStreamUrl.Unmarshal(m, b)
}
func (m *YoutubeStreamUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YoutubeStreamUrl.Marshal(b, m, deterministic)
}
func (m *YoutubeStreamUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YoutubeStreamUrl.Merge(m, src)
}
func (m *YoutubeStreamUrl) XXX_Size() int {
	return xxx_messageInfo_YoutubeStreamUrl.Size(m)
}
func (m *YoutubeStreamUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_YoutubeStreamUrl.DiscardUnknown(m)
}

var xxx_messageInfo_YoutubeStreamUrl proto.InternalMessageInfo

func (m *YoutubeStreamUrl) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type YoutubeParams struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsKeyActive          bool     `protobuf:"varint,4,opt,name=isKeyActive,proto3" json:"isKeyActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YoutubeParams) Reset()         { *m = YoutubeParams{} }
func (m *YoutubeParams) String() string { return proto.CompactTextString(m) }
func (*YoutubeParams) ProtoMessage()    {}
func (*YoutubeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{14}
}

func (m *YoutubeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YoutubeParams.Unmarshal(m, b)
}
func (m *YoutubeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YoutubeParams.Marshal(b, m, deterministic)
}
func (m *YoutubeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YoutubeParams.Merge(m, src)
}
func (m *YoutubeParams) XXX_Size() int {
	return xxx_messageInfo_YoutubeParams.Size(m)
}
func (m *YoutubeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_YoutubeParams.DiscardUnknown(m)
}

var xxx_messageInfo_YoutubeParams proto.InternalMessageInfo

func (m *YoutubeParams) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *YoutubeParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *YoutubeParams) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *YoutubeParams) GetIsKeyActive() bool {
	if m != nil {
		return m.IsKeyActive
	}
	return false
}

type Overlay struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	PointX               int32    `protobuf:"varint,5,opt,name=pointX,proto3" json:"pointX,omitempty"`
	PointY               int32    `protobuf:"varint,6,opt,name=pointY,proto3" json:"pointY,omitempty"`
	Show                 bool     `protobuf:"varint,7,opt,name=show,proto3" json:"show,omitempty"`
	CoverId              string   `protobuf:"bytes,8,opt,name=coverId,proto3" json:"coverId,omitempty"`
	Text                 string   `protobuf:"bytes,9,opt,name=text,proto3" json:"text,omitempty"`
	FontFamily           string   `protobuf:"bytes,10,opt,name=fontFamily,proto3" json:"fontFamily,omitempty"`
	FontSize             int32    `protobuf:"varint,11,opt,name=fontSize,proto3" json:"fontSize,omitempty"`
	LineHeight           float64  `protobuf:"fixed64,12,opt,name=lineHeight,proto3" json:"lineHeight,omitempty"`
	TextColor            string   `protobuf:"bytes,13,opt,name=textColor,proto3" json:"textColor,omitempty"`
	TextAlign            string   `protobuf:"bytes,14,opt,name=textAlign,proto3" json:"textAlign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Overlay) Reset()         { *m = Overlay{} }
func (m *Overlay) String() string { return proto.CompactTextString(m) }
func (*Overlay) ProtoMessage()    {}
func (*Overlay) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{15}
}

func (m *Overlay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Overlay.Unmarshal(m, b)
}
func (m *Overlay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Overlay.Marshal(b, m, deterministic)
}
func (m *Overlay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Overlay.Merge(m, src)
}
func (m *Overlay) XXX_Size() int {
	return xxx_messageInfo_Overlay.Size(m)
}
func (m *Overlay) XXX_DiscardUnknown() {
	xxx_messageInfo_Overlay.DiscardUnknown(m)
}

var xxx_messageInfo_Overlay proto.InternalMessageInfo

func (m *Overlay) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Overlay) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Overlay) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Overlay) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Overlay) GetPointX() int32 {
	if m != nil {
		return m.PointX
	}
	return 0
}

func (m *Overlay) GetPointY() int32 {
	if m != nil {
		return m.PointY
	}
	return 0
}

func (m *Overlay) GetShow() bool {
	if m != nil {
		return m.Show
	}
	return false
}

func (m *Overlay) GetCoverId() string {
	if m != nil {
		return m.CoverId
	}
	return ""
}

func (m *Overlay) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Overlay) GetFontFamily() string {
	if m != nil {
		return m.FontFamily
	}
	return ""
}

func (m *Overlay) GetFontSize() int32 {
	if m != nil {
		return m.FontSize
	}
	return 0
}

func (m *Overlay) GetLineHeight() float64 {
	if m != nil {
		return m.LineHeight
	}
	return 0
}

func (m *Overlay) GetTextColor() string {
	if m != nil {
		return m.TextColor
	}
	return ""
}

func (m *Overlay) GetTextAlign() string {
	if m != nil {
		return m.TextAlign
	}
	return ""
}

type Overlays struct {
	Overlays             []*Overlay `protobuf:"bytes,1,rep,name=overlays,proto3" json:"overlays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Overlays) Reset()         { *m = Overlays{} }
func (m *Overlays) String() string { return proto.CompactTextString(m) }
func (*Overlays) ProtoMessage()    {}
func (*Overlays) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{16}
}

func (m *Overlays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Overlays.Unmarshal(m, b)
}
func (m *Overlays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Overlays.Marshal(b, m, deterministic)
}
func (m *Overlays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Overlays.Merge(m, src)
}
func (m *Overlays) XXX_Size() int {
	return xxx_messageInfo_Overlays.Size(m)
}
func (m *Overlays) XXX_DiscardUnknown() {
	xxx_messageInfo_Overlays.DiscardUnknown(m)
}

var xxx_messageInfo_Overlays proto.InternalMessageInfo

func (m *Overlays) GetOverlays() []*Overlay {
	if m != nil {
		return m.Overlays
	}
	return nil
}

type BackgroundVideo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackgroundVideo) Reset()         { *m = BackgroundVideo{} }
func (m *BackgroundVideo) String() string { return proto.CompactTextString(m) }
func (*BackgroundVideo) ProtoMessage()    {}
func (*BackgroundVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{17}
}

func (m *BackgroundVideo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackgroundVideo.Unmarshal(m, b)
}
func (m *BackgroundVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackgroundVideo.Marshal(b, m, deterministic)
}
func (m *BackgroundVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackgroundVideo.Merge(m, src)
}
func (m *BackgroundVideo) XXX_Size() int {
	return xxx_messageInfo_BackgroundVideo.Size(m)
}
func (m *BackgroundVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackgroundVideo.DiscardUnknown(m)
}

var xxx_messageInfo_BackgroundVideo proto.InternalMessageInfo

func (m *BackgroundVideo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackgroundVideo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BackgroundVideo) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type BackgroundVideosResponse struct {
	Videos               []*BackgroundVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BackgroundVideosResponse) Reset()         { *m = BackgroundVideosResponse{} }
func (m *BackgroundVideosResponse) String() string { return proto.CompactTextString(m) }
func (*BackgroundVideosResponse) ProtoMessage()    {}
func (*BackgroundVideosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{18}
}

func (m *BackgroundVideosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackgroundVideosResponse.Unmarshal(m, b)
}
func (m *BackgroundVideosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackgroundVideosResponse.Marshal(b, m, deterministic)
}
func (m *BackgroundVideosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackgroundVideosResponse.Merge(m, src)
}
func (m *BackgroundVideosResponse) XXX_Size() int {
	return xxx_messageInfo_BackgroundVideosResponse.Size(m)
}
func (m *BackgroundVideosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackgroundVideosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackgroundVideosResponse proto.InternalMessageInfo

func (m *BackgroundVideosResponse) GetVideos() []*BackgroundVideo {
	if m != nil {
		return m.Videos
	}
	return nil
}

type VideoInfo struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Size                 string   `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoInfo) Reset()         { *m = VideoInfo{} }
func (m *VideoInfo) String() string { return proto.CompactTextString(m) }
func (*VideoInfo) ProtoMessage()    {}
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{19}
}

func (m *VideoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoInfo.Unmarshal(m, b)
}
func (m *VideoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoInfo.Marshal(b, m, deterministic)
}
func (m *VideoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoInfo.Merge(m, src)
}
func (m *VideoInfo) XXX_Size() int {
	return xxx_messageInfo_VideoInfo.Size(m)
}
func (m *VideoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VideoInfo proto.InternalMessageInfo

func (m *VideoInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *VideoInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VideoInfo) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

type UploadVideoRequest struct {
	// Types that are valid to be assigned to Data:
	//	*UploadVideoRequest_Info
	//	*UploadVideoRequest_Chunk
	Data                 isUploadVideoRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UploadVideoRequest) Reset()         { *m = UploadVideoRequest{} }
func (m *UploadVideoRequest) String() string { return proto.CompactTextString(m) }
func (*UploadVideoRequest) ProtoMessage()    {}
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{20}
}

func (m *UploadVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVideoRequest.Unmarshal(m, b)
}
func (m *UploadVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVideoRequest.Marshal(b, m, deterministic)
}
func (m *UploadVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVideoRequest.Merge(m, src)
}
func (m *UploadVideoRequest) XXX_Size() int {
	return xxx_messageInfo_UploadVideoRequest.Size(m)
}
func (m *UploadVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVideoRequest proto.InternalMessageInfo

type isUploadVideoRequest_Data interface {
	isUploadVideoRequest_Data()
}

type UploadVideoRequest_Info struct {
	Info *VideoInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadVideoRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadVideoRequest_Info) isUploadVideoRequest_Data() {}

func (*UploadVideoRequest_Chunk) isUploadVideoRequest_Data() {}

func (m *UploadVideoRequest) GetData() isUploadVideoRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UploadVideoRequest) GetInfo() *VideoInfo {
	if x, ok := m.GetData().(*UploadVideoRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (m *UploadVideoRequest) GetChunk() []byte {
	if x, ok := m.GetData().(*UploadVideoRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadVideoRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadVideoRequest_Info)(nil),
		(*UploadVideoRequest_Chunk)(nil),
	}
}

type UploadVideoResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadVideoResponse) Reset()         { *m = UploadVideoResponse{} }
func (m *UploadVideoResponse) String() string { return proto.CompactTextString(m) }
func (*UploadVideoResponse) ProtoMessage()    {}
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{21}
}

func (m *UploadVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVideoResponse.Unmarshal(m, b)
}
func (m *UploadVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVideoResponse.Marshal(b, m, deterministic)
}
func (m *UploadVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVideoResponse.Merge(m, src)
}
func (m *UploadVideoResponse) XXX_Size() int {
	return xxx_messageInfo_UploadVideoResponse.Size(m)
}
func (m *UploadVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVideoResponse proto.InternalMessageInfo

func (m *UploadVideoResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Song)(nil), "service.Song")
	proto.RegisterType((*SongPlaylist)(nil), "service.SongPlaylist")
	proto.RegisterType((*AudioResponse)(nil), "service.AudioResponse")
	proto.RegisterType((*StreamResponse)(nil), "service.StreamResponse")
	proto.RegisterType((*StatusResponse)(nil), "service.StatusResponse")
	proto.RegisterType((*SDP)(nil), "service.SDP")
	proto.RegisterType((*StatusNCSResponse)(nil), "service.StatusNCSResponse")
	proto.RegisterType((*TwitchStreamKey)(nil), "service.TwitchStreamKey")
	proto.RegisterType((*DevCredentials)(nil), "service.DevCredentials")
	proto.RegisterType((*UserAuth)(nil), "service.UserAuth")
	proto.RegisterType((*StreamParametersResponse)(nil), "service.StreamParametersResponse")
	proto.RegisterType((*SaveStreamParametersRequest)(nil), "service.SaveStreamParametersRequest")
	proto.RegisterType((*YoutubeStreamKey)(nil), "service.YoutubeStreamKey")
	proto.RegisterType((*YoutubeStreamUrl)(nil), "service.YoutubeStreamUrl")
	proto.RegisterType((*YoutubeParams)(nil), "service.YoutubeParams")
	proto.RegisterType((*Overlay)(nil), "service.Overlay")
	proto.RegisterType((*Overlays)(nil), "service.Overlays")
	proto.RegisterType((*BackgroundVideo)(nil), "service.BackgroundVideo")
	proto.RegisterType((*BackgroundVideosResponse)(nil), "service.BackgroundVideosResponse")
	proto.RegisterType((*VideoInfo)(nil), "service.VideoInfo")
	proto.RegisterType((*UploadVideoRequest)(nil), "service.UploadVideoRequest")
	proto.RegisterType((*UploadVideoResponse)(nil), "service.UploadVideoResponse")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 1323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x6d, 0x4f, 0x1b, 0xc7,
	0x13, 0xb7, 0x8d, 0x6d, 0xcc, 0x18, 0x08, 0x6c, 0x08, 0xb9, 0x38, 0x51, 0xc4, 0xff, 0xfe, 0x89,
	0x8a, 0xd4, 0xca, 0x54, 0xe4, 0x4d, 0xd5, 0xbc, 0x68, 0x1c, 0x13, 0x1a, 0x4a, 0x20, 0xe8, 0x1c,
	0xa2, 0xa4, 0xaa, 0x2a, 0x2d, 0xbe, 0xc1, 0x3e, 0x71, 0xdc, 0xba, 0x7b, 0x7b, 0x26, 0xee, 0x47,
	0xa8, 0xfa, 0x99, 0xfa, 0x6d, 0xfa, 0x3d, 0xaa, 0x7d, 0xb8, 0x07, 0x1f, 0x3e, 0x17, 0x9a, 0xf6,
	0xdd, 0xce, 0xec, 0xec, 0x6f, 0x7e, 0xb3, 0x33, 0xbb, 0x33, 0x00, 0x97, 0xd4, 0x0b, 0xda, 0x23,
	0xce, 0x04, 0x23, 0x8b, 0x21, 0xf2, 0xb1, 0xd7, 0xc7, 0xd6, 0xc3, 0x01, 0x63, 0x03, 0x1f, 0x77,
	0x94, 0xfa, 0x2c, 0x3a, 0xdf, 0xc1, 0xcb, 0x91, 0x98, 0x68, 0x2b, 0xfb, 0xf7, 0x32, 0x54, 0x7b,
	0x2c, 0x18, 0x10, 0x02, 0xd5, 0x80, 0x5e, 0xa2, 0x55, 0xde, 0x2a, 0x6f, 0x2f, 0x39, 0x6a, 0x2d,
	0x75, 0x23, 0x3a, 0x40, 0xab, 0xa2, 0x75, 0x72, 0x4d, 0x36, 0xa1, 0x4e, 0x23, 0x31, 0x64, 0xdc,
	0x5a, 0x50, 0x5a, 0x23, 0x91, 0x0d, 0xa8, 0xd1, 0xc8, 0xf5, 0x98, 0x55, 0x55, 0x6a, 0x2d, 0x48,
	0x6d, 0x9f, 0x8d, 0x91, 0x5b, 0x35, 0xad, 0x55, 0x02, 0xb1, 0x60, 0xf1, 0xcc, 0x13, 0x9c, 0x0a,
	0xb4, 0xea, 0x5b, 0xe5, 0xed, 0x9a, 0x13, 0x8b, 0xf6, 0x33, 0x58, 0x96, 0x6c, 0x4e, 0x7c, 0x3a,
	0xf1, 0xbd, 0x50, 0x90, 0xff, 0x43, 0x2d, 0x64, 0xc1, 0x20, 0xb4, 0xca, 0x5b, 0x0b, 0xdb, 0xcd,
	0xdd, 0x95, 0xb6, 0x09, 0xaa, 0x2d, 0xad, 0x1c, 0xbd, 0x67, 0x3f, 0x85, 0x95, 0x8e, 0xf4, 0xe6,
	0x60, 0x38, 0x62, 0x41, 0x88, 0xd2, 0x2b, 0x47, 0xea, 0x4e, 0x54, 0x30, 0x0d, 0x47, 0x0b, 0xf6,
	0x47, 0x58, 0xed, 0x09, 0x8e, 0xf4, 0x32, 0xb1, 0xdb, 0x84, 0xfa, 0x98, 0xf9, 0x91, 0x89, 0xba,
	0xec, 0x18, 0x89, 0xec, 0x40, 0x3d, 0x14, 0x54, 0x44, 0xa1, 0x8a, 0xbc, 0xb9, 0x7b, 0x3f, 0x75,
	0xab, 0xd4, 0x31, 0x80, 0x63, 0xcc, 0xec, 0x0f, 0x12, 0x3a, 0xbb, 0x23, 0x43, 0x1c, 0x71, 0x1c,
	0x7b, 0x78, 0x65, 0x48, 0xc4, 0x62, 0x7a, 0x51, 0x15, 0x4d, 0x4e, 0x5f, 0xd4, 0xa6, 0x74, 0x29,
	0xc9, 0xa9, 0x6b, 0x6d, 0x38, 0x46, 0xb2, 0xef, 0xc3, 0x42, 0x6f, 0xef, 0x84, 0xac, 0xc1, 0x42,
	0xe8, 0x8e, 0x4c, 0x72, 0xe4, 0xd2, 0xfe, 0x12, 0xd6, 0xb5, 0xcb, 0xe3, 0x6e, 0x2f, 0x1b, 0x10,
	0xed, 0x0b, 0x6f, 0x8c, 0xc6, 0xa9, 0x91, 0xec, 0xe7, 0x70, 0xe7, 0xdd, 0x95, 0x27, 0xfa, 0x43,
	0x7d, 0x01, 0x87, 0x38, 0x91, 0x88, 0x17, 0x38, 0x89, 0x11, 0x2f, 0x70, 0x92, 0x39, 0x5c, 0x99,
	0x3a, 0xfc, 0x13, 0xac, 0xee, 0xe1, 0xb8, 0xcb, 0xd1, 0xc5, 0x40, 0x78, 0xd4, 0x0f, 0x49, 0x0b,
	0x1a, 0x7d, 0xdf, 0xc3, 0x40, 0x1c, 0xb8, 0x06, 0x20, 0x91, 0x55, 0x20, 0xd8, 0xe7, 0x28, 0x4c,
	0xd5, 0x18, 0x29, 0x83, 0xbe, 0x30, 0x85, 0xfe, 0x18, 0x1a, 0xa7, 0x21, 0xf2, 0x4e, 0x24, 0x86,
	0xb2, 0xde, 0xfa, 0xcc, 0x4d, 0x6a, 0x50, 0xae, 0xed, 0xdf, 0xca, 0x60, 0x69, 0xd6, 0x27, 0x94,
	0xd3, 0x4b, 0x14, 0xc8, 0xc3, 0x6c, 0xa2, 0xaf, 0x3c, 0x57, 0x0c, 0xd5, 0x89, 0x9a, 0xa3, 0x05,
	0xe9, 0x6a, 0x88, 0xde, 0x60, 0xa8, 0x29, 0xd4, 0x1c, 0x23, 0xc9, 0x90, 0xcf, 0x47, 0xa1, 0xf2,
	0x5f, 0x73, 0xe4, 0x52, 0x5a, 0x8e, 0x38, 0x86, 0x28, 0x4c, 0xd5, 0x1a, 0x29, 0x53, 0x18, 0xb5,
	0x6c, 0x61, 0xd8, 0x11, 0x3c, 0xec, 0xd1, 0x31, 0x5e, 0xe7, 0xf3, 0x4b, 0x84, 0xa1, 0xf8, 0xaf,
	0xe8, 0xd8, 0x4f, 0x60, 0xed, 0x23, 0x8b, 0x44, 0x74, 0x86, 0x73, 0xf2, 0x77, 0xcd, 0xea, 0x94,
	0xfb, 0xd2, 0x2a, 0xe2, 0x7e, 0x6c, 0x15, 0x71, 0xdf, 0x66, 0xb0, 0x62, 0xac, 0x14, 0xff, 0x70,
	0x46, 0x21, 0x98, 0x43, 0x95, 0xe4, 0x90, 0xac, 0x66, 0x0c, 0xe8, 0x99, 0x8f, 0xae, 0xc9, 0x5e,
	0x2c, 0x92, 0x2d, 0x68, 0x7a, 0xe1, 0x21, 0x4e, 0x3a, 0x3a, 0xb7, 0x55, 0xb5, 0x9b, 0x55, 0xd9,
	0x7f, 0x56, 0x60, 0xf1, 0xed, 0x18, 0xb9, 0x4f, 0x27, 0x64, 0x15, 0x2a, 0x5e, 0x5c, 0x32, 0x15,
	0xcf, 0x95, 0x09, 0x17, 0x93, 0x51, 0xf2, 0xc1, 0xc8, 0x75, 0x7a, 0x89, 0x0b, 0xb3, 0x2f, 0xb1,
	0x3a, 0x75, 0x89, 0xf2, 0xca, 0x98, 0x17, 0x88, 0x0f, 0x2a, 0x53, 0x35, 0xc7, 0x48, 0x89, 0xfe,
	0xa3, 0xf9, 0x61, 0x8c, 0x24, 0x3d, 0x86, 0x43, 0x76, 0x65, 0x2d, 0x2a, 0xa2, 0x6a, 0x2d, 0xa3,
	0x53, 0xff, 0xd2, 0x81, 0x6b, 0x35, 0x14, 0x91, 0x58, 0x54, 0xfc, 0xf0, 0x93, 0xb0, 0x96, 0x0c,
	0x3f, 0xfc, 0x24, 0xc8, 0x63, 0x80, 0x73, 0x16, 0x88, 0x7d, 0x7a, 0xe9, 0xf9, 0x13, 0x0b, 0xd4,
	0x4e, 0x46, 0x23, 0x1f, 0x87, 0x94, 0x7a, 0xde, 0xaf, 0x68, 0x35, 0x95, 0xef, 0x44, 0x96, 0x67,
	0x7d, 0x2f, 0xc0, 0xd7, 0x3a, 0x92, 0x65, 0x55, 0x5b, 0x19, 0x0d, 0x79, 0x04, 0x4b, 0xd2, 0x47,
	0x97, 0xf9, 0x8c, 0x5b, 0x2b, 0x0a, 0x3a, 0x55, 0xc4, 0xbb, 0x1d, 0xdf, 0x1b, 0x04, 0xd6, 0x6a,
	0xba, 0xab, 0x14, 0xf6, 0x37, 0xd0, 0x30, 0xd7, 0x1c, 0x92, 0xaf, 0xa0, 0xc1, 0xcc, 0xda, 0xfc,
	0x9c, 0x6b, 0xc9, 0x17, 0x66, 0x8c, 0x9c, 0xc4, 0xc2, 0x3e, 0x82, 0x3b, 0x2f, 0x69, 0xff, 0x62,
	0xc0, 0x59, 0x14, 0xb8, 0xef, 0x3d, 0x17, 0xd9, 0xcc, 0x6e, 0xa0, 0x93, 0xa7, 0x6b, 0x58, 0x26,
	0xaf, 0xe8, 0x45, 0xbf, 0x01, 0x2b, 0x07, 0x97, 0x3e, 0xd8, 0xaf, 0xa1, 0x3e, 0x56, 0x1a, 0x43,
	0xcb, 0x4a, 0x68, 0xe5, 0x8e, 0x38, 0xc6, 0xce, 0x7e, 0x0b, 0x4b, 0x4a, 0x71, 0x10, 0x9c, 0x33,
	0x75, 0xb7, 0x9e, 0x8f, 0xc7, 0x29, 0xb5, 0x44, 0x9e, 0x59, 0x4b, 0x32, 0xdb, 0x32, 0x0f, 0xba,
	0x55, 0xa9, 0xb5, 0xfd, 0x33, 0x90, 0xd3, 0x91, 0xcf, 0xa8, 0xf1, 0x63, 0x9e, 0xee, 0x36, 0x54,
	0xbd, 0xe0, 0x9c, 0x29, 0xd4, 0xe6, 0x2e, 0x49, 0x68, 0x25, 0xbe, 0x5f, 0x97, 0x1c, 0x65, 0x41,
	0x36, 0xa1, 0xd6, 0x1f, 0x46, 0xc1, 0x85, 0x72, 0xb4, 0xfc, 0xba, 0xe4, 0x68, 0xf1, 0x65, 0x1d,
	0xaa, 0x2e, 0x15, 0xd4, 0x7e, 0x0a, 0x77, 0xa7, 0xf0, 0x4d, 0xe4, 0x69, 0xe9, 0xab, 0xdb, 0xdb,
	0xfd, 0x63, 0x1d, 0xaa, 0x47, 0xd4, 0x0b, 0xc8, 0x2b, 0x20, 0x5d, 0x8e, 0x54, 0xe0, 0x54, 0xe3,
	0xdb, 0x6c, 0xeb, 0xae, 0xdd, 0x8e, 0xbb, 0x76, 0xfb, 0x95, 0xec, 0xda, 0xad, 0x7b, 0x53, 0x1d,
	0x30, 0x36, 0xb7, 0x4b, 0x64, 0x1f, 0xee, 0x76, 0x23, 0xce, 0x31, 0x10, 0x9f, 0x87, 0xf3, 0x4a,
	0x5e, 0x8f, 0x9b, 0xa7, 0x33, 0xdb, 0xbc, 0x55, 0x80, 0x6e, 0x97, 0xc8, 0x17, 0xb0, 0x78, 0x62,
	0x1a, 0xde, 0x72, 0x7a, 0x76, 0xef, 0xa4, 0x35, 0x25, 0xd9, 0x25, 0xd2, 0x81, 0xe5, 0x9e, 0xa0,
	0x5c, 0xc4, 0xd6, 0x45, 0x84, 0x8b, 0x7a, 0xb0, 0x5d, 0x22, 0x2f, 0xa0, 0xd9, 0x13, 0x6c, 0xf4,
	0xb9, 0x08, 0x94, 0x0b, 0xfd, 0x71, 0xde, 0x08, 0x21, 0x3b, 0x48, 0xd8, 0x25, 0xf2, 0x1d, 0x80,
	0xe4, 0x70, 0x0b, 0x80, 0x1c, 0x85, 0xe7, 0x50, 0xd7, 0xba, 0x7f, 0x72, 0xf8, 0x00, 0xee, 0xf6,
	0xae, 0xe8, 0x28, 0xff, 0x8a, 0x0b, 0x5f, 0xd7, 0x9c, 0xc4, 0x75, 0xe1, 0xce, 0xbe, 0x17, 0xb8,
	0xc7, 0x78, 0x25, 0x33, 0x2d, 0xa7, 0x8b, 0x42, 0x42, 0xc5, 0x20, 0x1d, 0x58, 0x4a, 0x86, 0x93,
	0xc2, 0xe3, 0xad, 0x5c, 0x3c, 0x99, 0x41, 0x46, 0x87, 0x64, 0x46, 0x96, 0xa4, 0xe1, 0xca, 0xb6,
	0x97, 0x86, 0x94, 0x1b, 0x68, 0xe6, 0xb0, 0xf9, 0x01, 0x36, 0xba, 0x43, 0xec, 0x5f, 0xe4, 0x47,
	0xa0, 0x22, 0x62, 0x85, 0x3e, 0x14, 0xad, 0x7b, 0x7b, 0xe8, 0xa3, 0xc0, 0x9b, 0x82, 0x15, 0xd3,
	0x3a, 0x02, 0x4b, 0xc6, 0xa6, 0x81, 0x72, 0x13, 0x56, 0x9a, 0xeb, 0xe9, 0x8d, 0x39, 0x70, 0xc7,
	0xf0, 0x20, 0x13, 0x65, 0x0e, 0xef, 0xef, 0x6b, 0x6a, 0xfa, 0x80, 0xc2, 0x6b, 0x65, 0x23, 0xbd,
	0x21, 0x60, 0x31, 0xbf, 0x17, 0xb0, 0xae, 0x91, 0x3a, 0xfd, 0x3e, 0x86, 0xe1, 0x3b, 0x76, 0x81,
	0x01, 0x59, 0x4f, 0xfc, 0xc7, 0x43, 0xe0, 0x1c, 0x84, 0xb7, 0xb0, 0x96, 0x9f, 0xbc, 0x0a, 0x79,
	0xfc, 0x2f, 0xf7, 0x54, 0xaf, 0x0f, 0x8f, 0x76, 0x89, 0xbc, 0x87, 0x8d, 0x59, 0xe3, 0x1c, 0x79,
	0x92, 0x1e, 0x2e, 0x9e, 0xf6, 0xe6, 0x10, 0x3d, 0x84, 0x8d, 0x78, 0x12, 0x9b, 0x2a, 0xde, 0x07,
	0x09, 0x6e, 0x7e, 0x9c, 0x9b, 0x5b, 0xbd, 0x9b, 0x3a, 0x0f, 0xd7, 0x46, 0xc0, 0xdb, 0xe7, 0x60,
	0x16, 0x31, 0x39, 0x26, 0x16, 0x10, 0x3b, 0xe5, 0xfe, 0xad, 0x89, 0x49, 0xb8, 0xdb, 0x13, 0xdb,
	0x07, 0xa2, 0x8a, 0x77, 0x7a, 0x34, 0x2d, 0xc6, 0xc9, 0xd1, 0xd5, 0xf6, 0xea, 0xe3, 0x59, 0x39,
	0xa2, 0x01, 0x1d, 0xc4, 0x9c, 0x48, 0x81, 0xe9, 0x1c, 0x2a, 0xdf, 0x42, 0xf3, 0x7b, 0x14, 0xc9,
	0x28, 0x55, 0xc4, 0x61, 0x3d, 0x3f, 0x50, 0x85, 0xba, 0x42, 0xf3, 0xa3, 0xcf, 0x0d, 0x2a, 0xb4,
	0x68, 0x5a, 0xb2, 0x4b, 0xe4, 0x0d, 0x34, 0x33, 0xc3, 0x04, 0x79, 0x98, 0x3e, 0x97, 0x6b, 0x23,
	0x4c, 0xeb, 0xd1, 0xec, 0xcd, 0x18, 0x6b, 0xbb, 0x4c, 0x0e, 0xe3, 0xcf, 0xeb, 0x5f, 0x68, 0x14,
	0x2f, 0xeb, 0x3f, 0x56, 0xdb, 0x3b, 0xa3, 0xb3, 0xb3, 0xba, 0xda, 0x79, 0xf6, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x3a, 0xd0, 0x7a, 0x7c, 0x10, 0x00, 0x00,
}
