// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/songs.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Song struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page                 string   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Audio                string   `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Bitrate              int32    `protobuf:"varint,6,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{0}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Song) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Song) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Song) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

func (m *Song) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Song) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type Playlist struct {
	Songs                []*Song  `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Playlist) Reset()         { *m = Playlist{} }
func (m *Playlist) String() string { return proto.CompactTextString(m) }
func (*Playlist) ProtoMessage()    {}
func (*Playlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{1}
}

func (m *Playlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playlist.Unmarshal(m, b)
}
func (m *Playlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playlist.Marshal(b, m, deterministic)
}
func (m *Playlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playlist.Merge(m, src)
}
func (m *Playlist) XXX_Size() int {
	return xxx_messageInfo_Playlist.Size(m)
}
func (m *Playlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Playlist.DiscardUnknown(m)
}

var xxx_messageInfo_Playlist proto.InternalMessageInfo

func (m *Playlist) GetSongs() []*Song {
	if m != nil {
		return m.Songs
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Song)(nil), "service.Song")
	proto.RegisterType((*Playlist)(nil), "service.Playlist")
	proto.RegisterType((*Empty)(nil), "service.Empty")
}

func init() { proto.RegisterFile("proto/songs.proto", fileDescriptor_23af63290edd64ad) }

var fileDescriptor_23af63290edd64ad = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x8d, 0x6b, 0x5a, 0xfd, 0xc4, 0xc9, 0x82, 0x48, 0xf0, 0x54, 0xea, 0xa5, 0xa7, 0x16,
	0x26, 0xfe, 0x01, 0x45, 0xf0, 0x22, 0x48, 0xbd, 0x79, 0xfb, 0x3a, 0x3f, 0x6a, 0x61, 0x4d, 0x4a,
	0x92, 0x0d, 0xf6, 0x1f, 0xfc, 0xd1, 0x23, 0x5f, 0xb7, 0xde, 0xde, 0xe7, 0x49, 0xf2, 0xf2, 0x12,
	0x58, 0x8d, 0xce, 0x06, 0x5b, 0x7b, 0x6b, 0x3a, 0x5f, 0x71, 0x56, 0x99, 0x27, 0xb7, 0xef, 0x37,
	0x54, 0xfc, 0x0b, 0x48, 0xbe, 0xad, 0xe9, 0x94, 0x82, 0xc4, 0xe0, 0x40, 0x5a, 0xe4, 0xa2, 0xbc,
	0x6e, 0x38, 0x47, 0x37, 0x62, 0x47, 0xfa, 0x72, 0x72, 0x31, 0xab, 0x07, 0x48, 0x71, 0x17, 0xfe,
	0xac, 0xd3, 0x0b, 0xb6, 0x27, 0x52, 0xf7, 0x20, 0x71, 0xf7, 0xdb, 0x5b, 0x9d, 0xb0, 0x9e, 0x20,
	0xda, 0x8d, 0xdd, 0x93, 0xd3, 0x72, 0xb2, 0x0c, 0x4a, 0x43, 0xd6, 0xf6, 0xc1, 0x61, 0x20, 0x9d,
	0xe6, 0xa2, 0x94, 0xcd, 0x19, 0x8b, 0x1a, 0xae, 0xbe, 0xb6, 0x78, 0xd8, 0xf6, 0x3e, 0xa8, 0x27,
	0x90, 0x3c, 0x59, 0x8b, 0x7c, 0x51, 0xde, 0xac, 0x6f, 0xab, 0xd3, 0xe6, 0x2a, 0xee, 0x6d, 0xa6,
	0xb3, 0x22, 0x03, 0xf9, 0x3e, 0x8c, 0xe1, 0xb0, 0xfe, 0x80, 0xbb, 0xe8, 0xfd, 0x27, 0x1a, 0xec,
	0x68, 0x20, 0x13, 0xd4, 0x0b, 0x2c, 0xdf, 0x1c, 0x61, 0xa0, 0xb9, 0x72, 0x39, 0x77, 0xf0, 0xa3,
	0xc7, 0xd5, 0xcc, 0xe7, 0x2b, 0xc5, 0xc5, 0x6b, 0xfa, 0x93, 0x54, 0xf5, 0xd8, 0xb6, 0x29, 0x7f,
	0xd5, 0xf3, 0x31, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xb1, 0xcf, 0xd1, 0x3f, 0x01, 0x00, 0x00,
}
