// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/songs.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Song struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page                 string   `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Audio                string   `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Bitrate              int32    `protobuf:"varint,6,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{0}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Song) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Song) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Song) GetAudio() string {
	if m != nil {
		return m.Audio
	}
	return ""
}

func (m *Song) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Song) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type SongPlaylist struct {
	Songs                []*Song  `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongPlaylist) Reset()         { *m = SongPlaylist{} }
func (m *SongPlaylist) String() string { return proto.CompactTextString(m) }
func (*SongPlaylist) ProtoMessage()    {}
func (*SongPlaylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{1}
}

func (m *SongPlaylist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongPlaylist.Unmarshal(m, b)
}
func (m *SongPlaylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongPlaylist.Marshal(b, m, deterministic)
}
func (m *SongPlaylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongPlaylist.Merge(m, src)
}
func (m *SongPlaylist) XXX_Size() int {
	return xxx_messageInfo_SongPlaylist.Size(m)
}
func (m *SongPlaylist) XXX_DiscardUnknown() {
	xxx_messageInfo_SongPlaylist.DiscardUnknown(m)
}

var xxx_messageInfo_SongPlaylist proto.InternalMessageInfo

func (m *SongPlaylist) GetSongs() []*Song {
	if m != nil {
		return m.Songs
	}
	return nil
}

type AudioResponse struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioResponse) Reset()         { *m = AudioResponse{} }
func (m *AudioResponse) String() string { return proto.CompactTextString(m) }
func (*AudioResponse) ProtoMessage()    {}
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{2}
}

func (m *AudioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioResponse.Unmarshal(m, b)
}
func (m *AudioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioResponse.Marshal(b, m, deterministic)
}
func (m *AudioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioResponse.Merge(m, src)
}
func (m *AudioResponse) XXX_Size() int {
	return xxx_messageInfo_AudioResponse.Size(m)
}
func (m *AudioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AudioResponse proto.InternalMessageInfo

func (m *AudioResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type OutputResponse struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputResponse) Reset()         { *m = OutputResponse{} }
func (m *OutputResponse) String() string { return proto.CompactTextString(m) }
func (*OutputResponse) ProtoMessage()    {}
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{3}
}

func (m *OutputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputResponse.Unmarshal(m, b)
}
func (m *OutputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputResponse.Marshal(b, m, deterministic)
}
func (m *OutputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputResponse.Merge(m, src)
}
func (m *OutputResponse) XXX_Size() int {
	return xxx_messageInfo_OutputResponse.Size(m)
}
func (m *OutputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OutputResponse proto.InternalMessageInfo

func (m *OutputResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SDP struct {
	Sdp                  string   `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDP) Reset()         { *m = SDP{} }
func (m *SDP) String() string { return proto.CompactTextString(m) }
func (*SDP) ProtoMessage()    {}
func (*SDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_23af63290edd64ad, []int{5}
}

func (m *SDP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDP.Unmarshal(m, b)
}
func (m *SDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDP.Marshal(b, m, deterministic)
}
func (m *SDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDP.Merge(m, src)
}
func (m *SDP) XXX_Size() int {
	return xxx_messageInfo_SDP.Size(m)
}
func (m *SDP) XXX_DiscardUnknown() {
	xxx_messageInfo_SDP.DiscardUnknown(m)
}

var xxx_messageInfo_SDP proto.InternalMessageInfo

func (m *SDP) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

func init() {
	proto.RegisterType((*Song)(nil), "service.Song")
	proto.RegisterType((*SongPlaylist)(nil), "service.SongPlaylist")
	proto.RegisterType((*AudioResponse)(nil), "service.AudioResponse")
	proto.RegisterType((*OutputResponse)(nil), "service.OutputResponse")
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*SDP)(nil), "service.SDP")
}

func init() { proto.RegisterFile("proto/songs.proto", fileDescriptor_23af63290edd64ad) }

var fileDescriptor_23af63290edd64ad = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xb5, 0x89, 0x9d, 0xc0, 0x34, 0xad, 0xca, 0x00, 0xed, 0x2a, 0xa7, 0x68, 0x11, 0x90, 0x93,
	0x23, 0xb5, 0x12, 0x82, 0x43, 0x91, 0xa0, 0xe5, 0x88, 0x88, 0x6c, 0xb8, 0x70, 0xdb, 0x24, 0xa3,
	0xd4, 0x52, 0xe3, 0x5d, 0xed, 0x8e, 0x53, 0xe5, 0x0b, 0xb8, 0xf0, 0xd1, 0x68, 0xd7, 0x69, 0x90,
	0x6b, 0x10, 0x82, 0xdb, 0xbc, 0xe7, 0x37, 0xfb, 0xde, 0xcc, 0xc8, 0xf0, 0xd8, 0x58, 0xcd, 0x7a,
	0xea, 0x74, 0xb5, 0x72, 0x59, 0xa8, 0x71, 0xe0, 0xc8, 0x6e, 0xca, 0x05, 0xc9, 0x1f, 0x31, 0x24,
	0x85, 0xae, 0x56, 0x88, 0x90, 0x54, 0x6a, 0x4d, 0x22, 0x1e, 0xc7, 0x93, 0x47, 0x79, 0xa8, 0x3d,
	0x67, 0xd4, 0x8a, 0xc4, 0x83, 0x86, 0xf3, 0x35, 0x9e, 0x40, 0x5f, 0xd5, 0x7c, 0xad, 0xad, 0xe8,
	0x05, 0x76, 0x87, 0xf0, 0x29, 0xa4, 0xaa, 0x5e, 0x96, 0x5a, 0x24, 0x81, 0x6e, 0x80, 0x67, 0x17,
	0x7a, 0x43, 0x56, 0xa4, 0x0d, 0x1b, 0x00, 0x0a, 0x18, 0xcc, 0x4b, 0xb6, 0x8a, 0x49, 0xf4, 0xc7,
	0xf1, 0x24, 0xcd, 0xef, 0xa0, 0x3c, 0x87, 0xa1, 0x4f, 0x33, 0xbb, 0x51, 0xdb, 0x9b, 0xd2, 0x31,
	0x3e, 0x87, 0x34, 0xc4, 0x16, 0xf1, 0xb8, 0x37, 0x39, 0x38, 0x3b, 0xcc, 0x76, 0xb9, 0x33, 0xaf,
	0xca, 0x9b, 0x6f, 0xf2, 0x05, 0x1c, 0xbe, 0xf7, 0x6e, 0x39, 0x39, 0xa3, 0x2b, 0x47, 0xde, 0xd5,
	0x92, 0x5a, 0x6e, 0xc3, 0x30, 0x0f, 0xf3, 0x06, 0xc8, 0x97, 0x70, 0xf4, 0xb9, 0x66, 0x53, 0xf3,
	0x5f, 0x74, 0x03, 0x48, 0x3f, 0xae, 0x0d, 0x6f, 0xe5, 0x29, 0xf4, 0x8a, 0xab, 0x19, 0x1e, 0x43,
	0xcf, 0x2d, 0xcd, 0x6e, 0x31, 0xbe, 0x3c, 0xfb, 0x9e, 0xc0, 0x71, 0xc1, 0x96, 0xd4, 0xfa, 0x93,
	0xaa, 0xd4, 0x8a, 0xd6, 0x54, 0x31, 0x5e, 0x00, 0x5e, 0x5a, 0x52, 0x4c, 0xad, 0x01, 0x8e, 0xf6,
	0x89, 0xc3, 0x9b, 0xa3, 0x67, 0xad, 0x09, 0xee, 0x64, 0x32, 0xc2, 0x77, 0xf0, 0xe4, 0xb2, 0xb6,
	0x96, 0x2a, 0xfe, 0xbf, 0xfe, 0x0b, 0xc0, 0xaf, 0x66, 0x79, 0xdf, 0xfe, 0xf7, 0xf2, 0xd1, 0xbd,
	0x57, 0x65, 0x84, 0x6f, 0x61, 0xd8, 0x2c, 0xa7, 0x60, 0xc5, 0xb5, 0xeb, 0xf8, 0x9e, 0xee, 0x71,
	0x7b, 0x87, 0x32, 0xc2, 0x57, 0x30, 0x98, 0x59, 0xda, 0x94, 0x74, 0x8b, 0xc3, 0x5f, 0x76, 0x57,
	0xb3, 0x51, 0x0b, 0xc9, 0x08, 0xa7, 0x70, 0x50, 0xb0, 0xb2, 0xfc, 0xe5, 0xb6, 0xe4, 0xc5, 0x75,
	0xc7, 0xa2, 0x1b, 0xea, 0x35, 0x40, 0x68, 0x08, 0xd7, 0xed, 0xe8, 0x4f, 0xf6, 0xb8, 0x75, 0x7d,
	0x19, 0xe1, 0x9b, 0x9d, 0x51, 0x13, 0xf5, 0x5f, 0x66, 0xc9, 0xbc, 0xa3, 0x36, 0x7f, 0x68, 0xec,
	0x24, 0xfc, 0xd0, 0xff, 0x96, 0x64, 0x53, 0x33, 0x9f, 0xf7, 0xc3, 0x6f, 0x75, 0xfe, 0x33, 0x00,
	0x00, 0xff, 0xff, 0x36, 0x45, 0x38, 0x5c, 0x6b, 0x03, 0x00, 0x00,
}
